[package]
name = "mz-slt"
description = "sqllogictest"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rowan = "0.15.15"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]
